<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Default Kohana controller. This controller should NOT be used in production.
 * It is for demonstration purposes only!
 *
 * @package    Core
 * @author     Kohana Team
 * @copyright  (c) 2007-2008 Kohana Team
 * @license    http://kohanaphp.com/license.html
 */
class Todos_Controller extends Template_Controller {

  // Set the name of the template to use
  //public $template = 'kohana/template';

  public function index()
  {
    // In Kohana, all views are loaded and treated as objects.
    $this->template->content = new View('todolist');
    $this->template->title = 'Your to do list';

    $this->template->copyright = "&#169; Terry Morgan, ".Date('Y');
  }

  public function __call($method, $arguments)
  {
    // Disable auto-rendering
    $this->auto_render = FALSE;

    // By defining a __call method, all pages routed to this controller
    // that result in 404 errors will be handled by this method, instead of
    // being displayed as "Page Not Found" errors.
    echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
  }

} // End Welcome Controller